### PR TITLE
NeMo RTFx updates

### PR DESCRIPTION
**Pull request by galv**
Remove common voice from evaluation, as discussed.

Pin nemo to a particular version to make sure results are reproducible. In particular, include:
https://github.com/NVIDIA/NeMo/pull/10054

Make sure that optional dependency cuda-python is included to ensure that we use cuda graph accelerated decoder inference in RNN-T and TDT models.

~This is a *draft*. I will update it and let you know when it is ready @sanchit-gandhi . We're waiting on https://github.com/NVIDIA/NeMo/pull/10054 to merge.~ We are ready.

### CODE REVIEW

**Comment by galv** [comment]
[ASR HF Leaderboard - Galvez NeMo leaderboard results.pdf](https://github.com/user-attachments/files/16534447/ASR.HF.Leaderboard.-.Galvez.NeMo.leaderboard.results.pdf)

This table shows the results I obtained an an A100-80GB PCIe board.

image

**Review by pzelasko — COMMENTED** [review]
Looks good to me!

**Comment by nithinraok** [comment]
LGTM!

**Comment by sanchit-gandhi** [comment]
LGTM, thanks for the updates @galv! Feel free to merge when ready (title still has "Draft" so will leave it to you to decide!)

**Pull request merged**
